### ISSUE TITLE
Cardinality query with inconsistent results

### ISSUE THREAD

**Issue by fourcube** [protegeproject/dlquery#9]
I am having problems with DL queries that are based on object property cardinality and I am not sure if I am doing something wrong, or there is something wrong with HermiT / the DL Query engine.

First of all, I've attached a very simple ontology which demonstrates my problem. There are only two individuals **A** and **B** and the object property *hasSomething*. **A** *hasSomething* **B** is true.

The following DL Query returns **A** as a result:
```
hasSomething min 1
```
While the query

```
hasSomething exactly 1
```
cannot be satisfied.

```
# Turle format
@prefix : <http://www.semanticweb.org/cg/ontologies/2015/9/untitled-ontology-3#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <http://www.semanticweb.org/cg/ontologies/2015/9/untitled-ontology-3> .

<http://www.semanticweb.org/cg/ontologies/2015/9/untitled-ontology-3> rdf:type owl:Ontology .


#################################################################
#
#    Object Properties
#
#################################################################


###  http://www.semanticweb.org/cg/ontologies/2015/9/untitled-ontology-3#hasSomething

:hasSomething rdf:type owl:ObjectProperty .





#################################################################
#
#    Classes
#
#################################################################


###  http://www.semanticweb.org/cg/ontologies/2015/9/untitled-ontology-3#SimpleClass

:SimpleClass rdf:type owl:Class .





#################################################################
#
#    Individuals
#
#################################################################


###  http://www.semanticweb.org/cg/ontologies/2015/9/untitled-ontology-3#A

:A rdf:type owl:NamedIndividual ;

   :hasSomething :B .



###  http://www.semanticweb.org/cg/ontologies/2015/9/untitled-ontology-3#B

:B rdf:type owl:NamedIndividual .




###  Generated by the OWL API (version 3.5.1) http://owlapi.sourceforge.net
```

(I also posted this question on stackoverflow, but I figured, this might be a better place to ask. - http://stackoverflow.com/questions/33019902/cardinality-query-with-inconsistent-results)

**Comment by csnyulas** [comment]
This is correct. Because of the open world assumption (OWA) in OWL, from your assertions the reasoner cannot infer that A has no other "hasSomething" relationships to other individuals than B.

If you would modify your ontology to state that A is of type SimpleClass, and that SimpleClass is subclass of "hasSomething exactly 1", then the reasoner would return A as instance of both "hasSomething min 1" and "hasSomething exactly 1".
